server:
  port: 8761

eureka:
  instance:
    hostname: jingle-eureka
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
