spring:
  application:
    name: jingle-eureka

server:
  port: 14101

eureka:
  instance:
    hostname: jingle-eureka
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
#  server:
#    use-read-only-response-cache: true
#    response-cache-update-interval-ms : 30000

logging.path: /Users/pc-1900/vipkid/eureka
logging.file: eureka.log
